# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(966, 707)
        self.centralwidget = QtWidgets.QWidget(LoginWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(65, 100, 371, 531))
        self.label.setStyleSheet("border-image: url(:/images/images/BG.png);\n"
"border-radius:30px;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.Backgrand = QtWidgets.QLabel(self.centralwidget)
        self.Backgrand.setGeometry(QtCore.QRect(420, 120, 421, 490))
        self.Backgrand.setStyleSheet("background-color: rgba(255, 255, 255, 230);\n"
"border-top-right-radius:30px;\n"
"border-bottom-right-radius:30px;")
        self.Backgrand.setText("")
        self.Backgrand.setObjectName("Backgrand")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(500, 175, 251, 82))
        self.label_4.setStyleSheet("background-color: none;\n"
"border-image: url(:/images/images/hdline.png);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(430, 260, 401, 331))
        self.widget.setObjectName("widget")
        self.username_input = LineEdit(self.widget)
        self.username_input.setGeometry(QtCore.QRect(30, 50, 351, 51))
        font = QtGui.QFont()
        font.setFamily("得意黑")
        font.setPointSize(11)
        self.username_input.setFont(font)
        self.username_input.setStyleSheet("background-color: rgba(255, 255, 255, 180);\n"
"border-radius:8px;")
        self.username_input.setLocale(QtCore.QLocale(QtCore.QLocale.Chinese, QtCore.QLocale.China))
        self.username_input.setInputMethodHints(QtCore.Qt.ImhNone)
        self.username_input.setObjectName("username_input")
        self.password_input = PasswordLineEdit(self.widget)
        self.password_input.setGeometry(QtCore.QRect(30, 116, 351, 51))
        font = QtGui.QFont()
        font.setFamily("得意黑")
        font.setPointSize(11)
        self.password_input.setFont(font)
        self.password_input.setStyleSheet("background-color: rgba(255, 255, 255, 180);\n"
"border-radius:8px;")
        self.password_input.setLocale(QtCore.QLocale(QtCore.QLocale.Chinese, QtCore.QLocale.China))
        self.password_input.setInputMask("")
        self.password_input.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_input.setClearButtonEnabled(False)
        self.password_input.setObjectName("password_input")
        self.loginButton = QtWidgets.QPushButton(self.widget)
        self.loginButton.setGeometry(QtCore.QRect(40, 230, 331, 51))
        font = QtGui.QFont()
        font.setFamily("得意黑")
        font.setPointSize(11)
        self.loginButton.setFont(font)
        self.loginButton.setStyleSheet("#loginButton{\n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"    border:3px solid rgb(0,0,0);\n"
"    border-radius:8px\n"
"}\n"
"#loginButton:hover{\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"#loginButton:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px;\n"
"}")
        self.loginButton.setObjectName("loginButton")
        self.memory_checkBox = QtWidgets.QCheckBox(self.widget)
        self.memory_checkBox.setGeometry(QtCore.QRect(40, 181, 171, 19))
        font = QtGui.QFont()
        font.setFamily("得意黑")
        self.memory_checkBox.setFont(font)
        self.memory_checkBox.setStyleSheet("")
        self.memory_checkBox.setObjectName("memory_checkBox")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(790, 140, 31, 21))
        self.pushButton_2.setStyleSheet("border:none;\n"
"background-color: none;")
        self.pushButton_2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon)
        self.pushButton_2.setObjectName("pushButton_2")
        self.minimum = QtWidgets.QPushButton(self.centralwidget)
        self.minimum.setGeometry(QtCore.QRect(750, 140, 31, 20))
        self.minimum.setStyleSheet("border:none;\n"
"background-color: none;")
        self.minimum.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/minimized.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.minimum.setIcon(icon1)
        self.minimum.setObjectName("minimum")
        self.Backgrand.raise_()
        self.label_4.raise_()
        self.widget.raise_()
        self.pushButton_2.raise_()
        self.minimum.raise_()
        self.label.raise_()
        LoginWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(LoginWindow)
        self.pushButton_2.clicked.connect(LoginWindow.close) # type: ignore
        self.minimum.clicked.connect(LoginWindow.showMinimized) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "MainWindow"))
        self.username_input.setInputMask(_translate("LoginWindow", "nnnnnnnnnnnnnnnnn"))
        self.username_input.setPlaceholderText(_translate("LoginWindow", "教务系统账号："))
        self.password_input.setPlaceholderText(_translate("LoginWindow", "密码："))
        self.loginButton.setText(_translate("LoginWindow", "登录"))
        self.memory_checkBox.setText(_translate("LoginWindow", "记住，下次自动登录"))
from qfluentwidgets import LineEdit, PasswordLineEdit
import resource_rc
